```bash
python sample_pb2.py                             
Traceback (most recent call last):
  File "~/proto-debug/sample_pb2.py", line 26, in <module>
    from google.geo.type import viewport_pb2 as google_dot_geo_dot_type_dot_viewport__pb2
ImportError: cannot import name 'viewport_pb2' from 'google.geo.type' (~/proto-debug/.venv/lib/python3.12/site-packages/google/geo/type/__init__.py)
```
